### PR TITLE
Update version to 2.2.0 for release

### PR DESCRIPTION
**Pull request by sfc-gh-rcheng**
!! v2.2.0 will not be released until beginning of February 2024 !!
This commit updates the version to v2.2.0 which will contain everything before this commit in the master branch

### CODE REVIEW

**Comment by sfc-gh-japatel** [comment]
can we wait for this push, we still have few commits in flight? (We can still push it but having version bump at ends helps)

**Review by sfc-gh-tzhang — APPROVED** [review]
PR itself looks good, but let's merge it when we're ready with the release, thanks!

**Comment by sfc-gh-rcheng** [comment]
Sounds good. holding this PR until 1/29 at the latest

**Comment by sfc-gh-xhuang** [comment]
Please rebase from master

**Pull request merged**
