### PR TITLE
NO-SNOW Ignore major updates on Kafka dependencies

### PR DESCRIPTION
**Pull request by sfc-gh-mbobowski**
# Overview

NO-SNOW Ignore major updates on Kafka dependencies

Dependabot gets confused with Confluent Kafka versioning and wants to update to community edition like [here](https://github.com/snowflakedb/snowflake-kafka-connector/pull/902/files). Preventing major updates should stop this behavior because ce / cs updates are not present in 3.x.x ([source](https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients?repo=confluent-packages))

## Pre-review checklist
- [ ] This change should be part of a Behavior Change Release. See [go/behavior-change](http://go/behavior-change).
- [ ] This change has passed Merge gate tests
- [ ] Snowpipe Changes
- [ ] Snowpipe Streaming Changes
- [ ] This change is TEST-ONLY
- [ ] This change is README/Javadocs only
- [ ] This change is protected by a config parameter <PARAMETER_NAME> eg `snowflake.ingestion.method`.
    - [ ] `Yes` - Added end to end and Unit Tests. 
    - [ ] `No` - Suggest why it is not param protected
- [ ] Is his change protected by parameter <PARAMETER_NAME> on the server side?
    - [ ] The parameter/feature is not yet active in production (partial rollout or PrPr, see [Changes for Unreleased Features and Fixes](http://go/ppp-prpr)).
    - [ ] If there is an issue, it can be safely mitigated by turning the parameter off. This is also verified by a test (See [go/ppp](http://go/ppp)).

### CODE REVIEW

**Review by sfc-gh-dseweryn — APPROVED** [review]
I was thinking that there may be a better way to make dependabot what we want but apparently there is no easy way. We should probably spend the time elsewhere. Question though — how will we keep the kafka updated? There are already versions 3.7.1 and 3.8.0 available.

**Comment by sfc-gh-mbobowski** [comment]
> I was thinking that there may be a better way to make dependabot what we want but apparently there is no easy way. We should probably spend the time elsewhere. Question though — how will we keep the kafka updated? There are already versions 3.7.1 and 3.8.0 available.

@sfc-gh-dseweryn not sure if I understand your question. The dependabot will keep track of the new Kafka releases that are not major so basically anything 3.x.y is valid.

**Comment by sfc-gh-dseweryn** [comment]
> There are already versions 3.7.1 and 3.8.0 available.

This was only a side-note that we're not on top of the available versions.
I meant that if 4.0.0 will be released we won't notice

**Comment by sfc-gh-mbobowski** [comment]
> > There are already versions 3.7.1 and 3.8.0 available.
> 
> This was only a side-note that we're not on top of the available versions. I meant that if 4.0.0 will be released we won't notice

That's true we have to track it on our own.

**Pull request merged**
