### PR TITLE
Modify pom.xml to use jdbc defined in connector and not from ingest sdk

### PR DESCRIPTION
**Pull request by sfc-gh-japatel**
Background:

- After upgrading ingest sdk to 1.0.3-beta, GCS tests started failing. 
- Above version uses jdbc 3.13.18

- We have our own native jdbc dependency at 3.13.23. 
- Intellij bytecode never showed code corresponding to 3.13.23 and always picked up from 3.13.18 (From Ingest SDK)

Root cause:
- Previously the jdbc dependency was defined after ingest SDK and APPARENTLY ORDERING MATTERS

Solution:
- Exclude jdbc from ingest SDK. 
- Define our own jdbc version in Connector. 

Next steps:
- Fix JDBC version in Ingest SDK to use 3.13.23 instead of 3.13.18

Few more changes:
- Use fail fast strategy to not kill other running tasks in matrix if one fails. We want all of them to run parallely. 
- Fix broken tests after allowed data type formats changed in latest version of ingest SDK. 

**MAVEN  DEPENDENCY  RANT.. SCREEEAMMMM**

### CODE REVIEW

**Review by sfc-gh-tjones — APPROVED** [review]

**Comment by sfc-gh-tzhang** [comment]
> Background:
> 
> * After upgrading ingest sdk to 1.0.3-beta, GCS tests started failing.
> * Above version uses jdbc 3.13.18
> * We have our own native jdbc dependency at 3.13.23.
> * Intellij bytecode never showed code corresponding to 3.13.23 and always picked up from 3.13.18 (From Ingest SDK)
> 
> Root cause:
> 
> * Previously the jdbc dependency was defined after ingest SDK and APPARENTLY ORDERING MATTERS
> 
> Solution:
> 
> * Exclude jdbc from ingest SDK.
> * Define our own jdbc version in Connector.
> 
> Next steps:
> 
> * Fix JDBC version in Ingest SDK to use 3.13.23 instead of 3.13.18
> 
> **MAVEN DEPENDENCY RANT.. SCREEEAMMMM**

This is interesting, we have a similar issue reported by the connector folks after upgrading the JDBC to 3.13.18, what's the failure message? Do you know whether it only happens in GCS?

**Comment by sfc-gh-japatel** [comment]
> > Background:
> > 
> > * After upgrading ingest sdk to 1.0.3-beta, GCS tests started failing.
> > * Above version uses jdbc 3.13.18
> > * We have our own native jdbc dependency at 3.13.23.
> > * Intellij bytecode never showed code corresponding to 3.13.23 and always picked up from 3.13.18 (From Ingest SDK)
> > 
> > Root cause:
> > 
> > * Previously the jdbc dependency was defined after ingest SDK and APPARENTLY ORDERING MATTERS
> > 
> > Solution:
> > 
> > * Exclude jdbc from ingest SDK.
> > * Define our own jdbc version in Connector.
> > 
> > Next steps:
> > 
> > * Fix JDBC version in Ingest SDK to use 3.13.23 instead of 3.13.18
> > 
> > **MAVEN DEPENDENCY RANT.. SCREEEAMMMM**
> 
> This is interesting, we have a similar issue reported by the connector folks after upgrading the JDBC to 3.13.18, what's the failure message? Do you know whether it only happens in GCS?

Yes, I only saw this in GCS. The error message is not very descriptive and I tried debugging JDBC with no luck. But it looks like `upload with presigned url failed.` I have asked ecosystem team about this.

**Comment by sfc-gh-japatel** [comment]
All end to end tests are failing in apache kafka and confluent, I will continue to investigate this, ingest SDK was the only thing that was upgraded.

**Comment by sfc-gh-japatel** [comment]
> All end to end tests are failing in apache kafka and confluent, I will continue to investigate this, ingest SDK was the only thing that was upgraded.

The issue is with the date `'APPROVAL_DATE': '15-Jun-2022',` column in `test_schema_mapping.py` test. 

Great test and love how it failed. 

CC: @sfc-gh-tzhang confirming this is expected behavior as I see this in change logs too.

**Pull request merged**
