### PR TITLE
Add JSON_SR Snowflake Converter

### PR DESCRIPTION
**Pull request by nachomdo**
This PR brings a new custom Snowflake converter that supports JSON_SR format. 

Fixes: https://github.com/snowflakedb/snowflake-kafka-connector/issues/481

### CODE REVIEW

**Comment by nachomdo** [comment]
👋  @sfc-gh-japatel @sfc-gh-tzhang  @sfc-gh-tjones @sfc-gh-rcheng Could I get a review, please? Thanks! 😊

**Comment by sfc-gh-japatel** [comment]
Hi @nachomdo thanks for the contribution. 
Can you please add a description on why we need this change?

Few concerns about one more converter. 
- We introduced converter in past to have better error handling. 
- In our recent release of snowpipe streaming and kafka connector (version > 1.8.0) we have deprecated custom snowflake converters in lieu of not adding more customizations and supporting only community converters. 
- One of the important reasons to do the deprecation was use of DLQ for error handling. These Snowflake* converters wont send data to DLQ but into a table stage in [Snowflake](https://docs.snowflake.com/en/sql-reference/sql/create-stage.html)

**Comment by nachomdo** [comment]
Thanks for your reply above, @sfc-gh-japatel 😊 We are trying to use the Snowflake Sink connector with a topic that contains JSON_SR format. If we use the current SnowflakeJSONConverter we get an error due to the [magic number + schemaID bytes](https://rmoff.net/2020/07/03/why-json-isnt-the-same-as-json-schema-in-kafka-connect-converters-and-ksqldb-viewing-kafka-messages-bytes-as-hex/) prepended to the record JSON payload when using JSON_SR. This manifest in parsing errors like the one described in https://github.com/snowflakedb/snowflake-kafka-connector/issues/481. I have also tried with JsonSchemaConverter but then the error happens when trying to write to the Snowflake table.

I will try 1.8.0 release and see if that works with the JsonSchemaConverter. If that's the case I will close this ASAP. Thanks so much! 😊

**Comment by sfc-gh-japatel** [comment]
Thanks @nachomdo 

version 1.8.2 doesnt have snowpipe streaming enabled by default. 
You will have to first opt into the feature by asking the sales representative and also using ingestion method as snowpipe streaming. (Or you can tell me the account name for snowflake and I can enable it for you)

**Comment by nachomdo** [comment]
Thanks @sfc-gh-japatel ! We will try your suggestion next week and let you know if that solved the issue. Thanks again! 😊

**Comment by nachomdo** [comment]
Thanks @sfc-gh-japatel ! It works with snowpipe streaming so I'm closing this PR 😃

**Pull request closed without merging**
