### PR TITLE
Transfer ownership of project in CODEOWNERS file. Change streaming-ingest to snowpipe kafka team

### PR DESCRIPTION
**Pull request by sfc-gh-nsienkiewicz-1**
# Overview
NO-SNOW

As a part of project handoff, we need to change CODEOWNERS. My team feels confident that we can take over full ownership.

## Pre-review checklist
- [ ] This change should be part of a Behavior Change Release. See [go/behavior-change](http://go/behavior-change).
- [ ] This change has passed Merge gate tests
- [ ] Snowpipe Changes
- [ ] Snowpipe Streaming Changes
- [ ] This change is TEST-ONLY
- [ ] This change is README/Javadocs only
- [ ] This change is protected by a config parameter <PARAMETER_NAME> eg `snowflake.ingestion.method`.
    - [ ] `Yes` - Added end to end and Unit Tests. 
    - [ ] `No` - Suggest why it is not param protected
- [ ] Is his change protected by parameter <PARAMETER_NAME> on the server side?
    - [ ] The parameter/feature is not yet active in production (partial rollout or PrPr, see [Changes for Unreleased Features and Fixes](http://go/ppp-prpr)).
    - [ ] If there is an issue, it can be safely mitigated by turning the parameter off. This is also verified by a test (See [go/ppp](http://go/ppp)).

### CODE REVIEW

**Review by sfc-gh-japatel — APPROVED** [review]
lgtm!

**Comment by sfc-gh-tzhang** [comment]
> As a part of project handoff, we need to change CODEOWNERS. My team feels confident that we can take over full ownership.

Should we wait until end of this month or you believe the team is ready as of today? This means that we won't have any PR request unless being added explicitly.

**Review by sfc-gh-rcheng — APPROVED** [review]
this feels like a very monumental pr, lgtm!

**Comment by sfc-gh-nsienkiewicz-1** [comment]
> > As a part of project handoff, we need to change CODEOWNERS. My team feels confident that we can take over full ownership.
> 
> Should we wait until end of this month or you believe the team is ready as of today? This means that we won't have any PR request unless being added explicitly.

@sfc-gh-tzhang the team feels confident about it. I talked with @sfc-gh-psaraiya - I will merge this PR after the May Kafka Connector release.

**Comment by sfc-gh-tzhang** [comment]
> > Should we wait until end of this month or you believe the team is ready as of today? This means that we won't have any PR request unless being added explicitly.
> 
> @sfc-gh-tzhang the team feels confident about it. I talked with @sfc-gh-psaraiya - I will merge this PR after the May Kafka Connector release.

Thanks for confirming, we just had a release done a few days ago if that's what you mean by May release

**Review by sfc-gh-tzhang — APPROVED** [review]

**Review by sfc-gh-xhuang — APPROVED** [review]

**Review by sfc-gh-psaraiya — APPROVED** [review]

**Review by sfc-gh-wtrefon — APPROVED** [review]

**Pull request merged**
