### PR TITLE
Remove travis test

### PR DESCRIPTION
**Pull request by sfc-gh-zli**

### CODE REVIEW

**Review by sfc-gh-japatel — APPROVED** [review]
lgtm

**Review by sfc-gh-bli — APPROVED** [review]

**Comment by sfc-gh-japatel** [comment]
Should we also remove the profile.json.enc?

**Comment by sfc-gh-zli** [comment]
We need to update profile.json.enc as pk rotates. To re-enable all test. Removing the yaml file should be sufficient for stoping Travis test.

**Comment by sfc-gh-japatel** [comment]
> We need to update profile.json.enc as pk rotates. To re-enable all test. Removing the yaml file should be sufficient for stoping Travis test.

I was under impression that profile.json.enc is only used for travis test. We use profile.json.gpg for GH Action tests.

**Comment by sfc-gh-japatel** [comment]
So for us to re-enable all failed tests, we will need to update the gpp in .github/script folder. I will do that in upcoming PR.

**Pull request merged**
