### PR TITLE
PROD-39429 Implement migrate sys func from new channel(Format V2) to old channel (V1)

### PR DESCRIPTION
**Pull request by sfc-gh-japatel**
This is a long term implementation for potential data duplication introduced because of a new channel name format. 
- It is about moving away for customers who might have onboarded to new channel format which was introduced in version 2.1.0 (Now de-listed)
- We will stick to old format for new customers running this for the first time. 
- Renamed channelName to channelNameFormatV1 and introduced `channelNameFormatV2`

Added tests in `TopicPartitionChannel` and `TopicPartitionChannel`

Notes:
- This PR is opened against [japatel-SNOW-971412-release-2-1-1-ready](https://github.com/snowflakedb/snowflake-kafka-connector/tree/japatel-SNOW-971412-release-2-1-1-ready) which is going to be the release branch for v2.1.1
- A similar PR will also be opened against master. 

End to End tests:
1. Use 2.1.0
2. Use two connectors:
3. Uses channel Name v2
Screenshot 2023-11-20 at 4 54 59 PM
4. Stop 
5. Replace jar (2.1.1) and restart. 
6. Does the migration and you can only see old channel format
Screenshot 2023-11-20 at 5 17 59 PM

7.  Stop again and restart in 2.1.1
Nothing happens and we do get a valid response saying newchannelFormatV2 doesnt exist
Screenshot 2023-11-20 at 5 18 11 PM

### CODE REVIEW

**Review by sfc-gh-tzhang — COMMENTED** [review]
The change should be merged into master first and then port to this branch?

**Comment by sfc-gh-japatel** [comment]
> The change should be merged into master first and then port to this branch?

Does the order matter? (I dont think so)
Lot of merge conflicts on main hence two different PRs. Also, the commit will be needed in release branch 2.1.1 anyways. 

Since you have commented on other one, lets get the discussion their and I will make sure its cp'ed in this branch too.

**Comment by sfc-gh-japatel** [comment]
@sfc-gh-tzhang @sfc-gh-rcheng I am going to push this to the release branch [japatel-SNOW-971412-release-2-1-1-ready](https://github.com/snowflakedb/snowflake-kafka-connector/tree/japatel-SNOW-971412-release-2-1-1-ready)

This branch will be used to release 2.1.1 (No need to update the release version)

**Comment by sfc-gh-japatel** [comment]
FYI, the tests were failing if I had schematization enabled and the first batch was missing on target table. Hence the new test I added had schematization off. I think this got fixed in later versions and is not a problem in main but we should be aware of this in this version.

CC: @sfc-gh-tzhang @sfc-gh-rcheng

**Pull request merged**
