### PR TITLE
Update to 2.0.2 Ingest SDK

### PR DESCRIPTION
**Pull request by sfc-gh-rcheng**
Ingest SDK GA'ed 🎉 lets use the newest version

### CODE REVIEW

**Review by sfc-gh-japatel — APPROVED** [review]
Wohoo, lets go 🚀

**Review by sfc-gh-tzhang — CHANGES_REQUESTED** [review]
Ship it!

**Review by sfc-gh-tzhang — APPROVED** [review]

**Review by sfc-gh-tjones — APPROVED** [review]

**Comment by sfc-gh-rcheng** [comment]
license isnt passing, closing bc we may need release today

**Comment by sfc-gh-xhuang** [comment]
Is this PR still necessary? Saw some overlap with #676

**Comment by sfc-gh-rcheng** [comment]
not necessary, i reopened to show the license snyk merge gate issues

**Pull request closed without merging**
