### PR TITLE
updated to add password support

### PR DESCRIPTION
**Pull request by sql-dr-watson**

### CODE REVIEW

**Comment by sfc-gh-japatel** [comment]
Hey, why do you need this?

**Comment by sql-dr-watson** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/issues/319

HashiCorp Vault Snowflake Provider does not support RSA Tokens, but does do User/Pass

**Comment by sql-dr-watson** [comment]
https://www.vaultproject.io/api-docs/secret/databases/snowflake

**Comment by sfc-gh-japatel** [comment]
How is the password you added as a config, used to connect to snowflake? Sorry, I dont think I quite understand this. Can you describe a usecase?

**Comment by sql-dr-watson** [comment]
@sfc-gh-japatel 
The use case is for us to be able to use username & password instead of RSA Key Pair auth in the snowflake kafka connect worker config.  
So instead of 
snowflake.username
snowflake.privateKey
snowflake.privateKeyPassphrase

we would just set
snowflake.username
snowflake.password

**Comment by sfc-gh-japatel** [comment]
I am still confused here and not 100% clear on what the username and password are used for. 

This kafka connector internally uses snowpipe REST API which uses key pair based authentication. 
https://docs.snowflake.com/en/user-guide/data-load-snowpipe-rest-load.html
https://docs.snowflake.com/en/user-guide/data-load-snowpipe-rest-gs.html#step-3-configure-security-per-user

Can you please elaborate on how this username and password will be used? Are these stored in hashicorp? If yes, there is no way for us to fetch that from KC. 

May be this is a feature request for hashicorp to generate a key pair based authentication from username and password?

**Pull request closed without merging**
