### PR TITLE
Create release v2.0.0 for GA

### PR DESCRIPTION
**Pull request by sfc-gh-rcheng**
Title

[Diff](https://github.com/snowflakedb/snowflake-kafka-connector/compare/v1.9.4...rcheng-rel2.0.0) with last release (v1.9.4). Literally just sdk and version upgrades

Will not be taking the JMX changes - which is just this pr: https://github.com/snowflakedb/snowflake-kafka-connector/pull/672

Will be taking this revert - https://github.com/snowflakedb/snowflake-kafka-connector/pull/678

### CODE REVIEW

**Comment by sfc-gh-rcheng** [comment]
waiting for this pr go to through first
https://github.com/snowflakedb/snowflake-kafka-connector/pull/675

**Comment by sfc-gh-xhuang** [comment]
Does this release fix the https://github.com/snowflakedb/snowflake-kafka-connector/issues/669 issue?

**Comment by sfc-gh-tzhang** [comment]
Ideally we shouldn't include https://github.com/snowflakedb/snowflake-kafka-connector/pull/672, but it's fine if you believe it's a low risk change.

**Comment by sfc-gh-tzhang** [comment]
> Will not be taking the JMX changes - which is just this pr: #672

Then why we're merging this to master? I thought we should create a release branch base on 1.9.4, then create another new branch on top, so the PR should be merged from the new branch to the release branch

**Review by sfc-gh-tzhang — APPROVED** [review]
Ship it! A bit confused since you mentioned the JMX change won't be included, but it's actually included, so I assume the release will be from anther branch that exclude the change (or based on 1.9.4 + cherrypick), let me know if you need help.

**Comment by sfc-gh-rcheng** [comment]
> > Will not be taking the JMX changes - which is just this pr: #672
> 
> Then why we're merging this to master? I thought we should create a release branch base on 1.9.4, then create another new branch on top, so the PR should be merged from the new branch to the release branch

#672 is not included. I cherry picked two PRs on top of v1.9.4. It is confusing why github doesn't show the correct diff, however if you look at the [diff](https://github.com/snowflakedb/snowflake-kafka-connector/compare/v1.9.4...rcheng-rel2.0.0) i linked, you can see #672 is not included.

**Pull request merged**
