### PR TITLE
Release version 1.9.4

### PR DESCRIPTION
**Pull request by sfc-gh-rcheng**
Upgrades version to 1.9.4. See tag for rel notes

Testing
- Load tests: IP
- Chaos tests: IP

### CODE REVIEW

**Review by sfc-gh-japatel — APPROVED** [review]
lgtm!

**Review by sfc-gh-japatel — CHANGES_REQUESTED** [review]
Lets also modify Utils.java version

**Comment by sfc-gh-japatel** [comment]
This is still in draft, do you want to mark ready for review?

**Review by sfc-gh-japatel — APPROVED** [review]

**Comment by sfc-gh-rcheng** [comment]
I don't want to merge this until we have run the necessary tests

**Review by sfc-gh-tzhang — APPROVED** [review]

**Review by sfc-gh-asen — APPROVED** [review]

**Comment by sfc-gh-rcheng** [comment]
Tests run: https://drive.google.com/drive/folders/1Voy-i7dHKudtf8n_0YIUdFtlmK6sNZ2W?usp=drive_link
Results look good, ready to merge and begin release process

**Pull request merged**
