### PR TITLE
Added github actions which runs against GCS storage in Snowflake

### PR DESCRIPTION
**Pull request by sfc-gh-japatel**
- Tested using github actions on local machine. (Using github act)
  - `act -W .github/workflows/End2EndTestConfluentGCS.yml -v -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04`
- Added SECRET passphrase in github.
- This is required to verify performance of future put API changes

Future:
- Will add Stress test after all these new tests passes on PR.

### CODE REVIEW

**Review by sfc-gh-rramachandran — COMMENTED** [review]
Looks like the GCS test run failed, will wait for it to be green before signing off.

**Comment by sfc-gh-japatel** [comment]
> Looks like the GCS test run failed, will wait for it to be green before signing off.

Yes, looks like it is a valid failure. I will need to make a code change to not use putwith cache api if gcs is used.

**Comment by sfc-gh-japatel** [comment]
> > Looks like the GCS test run failed, will wait for it to be green before signing off.
> 
> Yes, looks like it is a valid failure. I will need to make a code change to not use putwith cache api if gcs is used.

I have modified the failed test to match the current scenario of code. i.e use putWithCache for AWS and Azure and use plain put api with connection for GCP. 

IngestStageIT test is the one to look for.

**Review by sfc-gh-rramachandran — APPROVED** [review]
LGTM!

**Review by sfc-gh-zli — APPROVED** [review]

**Pull request merged**
